# Generated by Django 4.0.4 on 2022-05-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=26)),
                ('email', models.EmailField(max_length=143)),
                ('team', models.TextField(max_length=26)),
                ('bday', models.DateField()),
            ],
        ),
    ]
