# Generated by Django 3.2.13 on 2022-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisher', '0005_delete_wishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet', models.TextField(max_length=500)),
            ],
        ),
    ]
