# Generated by Django 3.2.13 on 2022-05-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisher', '0006_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='prop',
        ),
    ]
