# Generated by Django 3.2.13 on 2022-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisher', '0007_rename_name_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='attach',
            field=models.ImageField(default='default.jpg', upload_to='any'),
        ),
    ]
