# Generated by Django 3.2.13 on 2022-05-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisher', '0008_prop_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='attach',
        ),
    ]
