# Generated by Django 3.2.13 on 2022-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisher', '0011_auto_20220515_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orga',
            name='ex',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orig',
            name='secro',
            field=models.EmailField(max_length=254),
        ),
    ]
